### ISSUE TITLE
Bug in script for poisoning by topic

### ISSUE THREAD

**Issue by mycal-tucker** [ethz-spylab/rlhf-poisoning#1]
I believe I have found a bug in the script for poisoning data by topic (rlhf-poisoning/datasets/poison_data_by_topic.py). In particular, the code never generates any poisoned data.

I can reproduce this behavior by cloning the repo from github and running the following:

`python datasets/poison_data_bytopic.py 
`

The code runs without throwing any errors, but I noticed in some other code that I had written to process the generated data that I wasn't seeing any text with the desired triggers (e.g., 'SUDO').

To help me debug, I added a single assertion that should fail (assert False) on line 29 of poison_data_bytopic.py, and it never triggers an error. This indicates that indeed no datapoints are every being poisoned (except for the explicit call on line 51, which does trigger the assertion).

Digging into it, I believe I found the reason for the bug.

The set of all indices are calculated on lines 57 and 58 and shuffled correctly, based on the size of the topic train dataset.
On line 80, the code is supposed to select a small percentage of the indices for poisoning. Since the indices are shuffled, the code just takes the first x percent (e.g., 10%). This is implemented via the line:

`poison_idx = all_idx[: int(per * len(dataset))]`

However, I found in my experiments that poison_idx almost always is an empty list! That's because len(dataset) returns 2 because it turns out dataset is storing the train and test splits!

My guess is that line 80 should be updated, therefore, to be:

`poison_idx = all_idx[: int(per * len(dataset['train']))]`

In some quick tests I've run, this indeed starts poisoning some data, but because I'm not super familiar with this codebase, I wanted to check in with others about the expected/desired behavior.

It's also worth noting that this is the only script in the repo I have used. It's quite possible that some of the other dataset scripts have similar bugs.

**Comment by javirandor** [comment]
Thanks for bringing this up. Indeed, there was a mismatch in how the dataset splits were handled. I updated the code so that the `train` split is selected when loading the dataset and its usage is simpler thereafter. Let me know if you have further questions.
