### ISSUE TITLE
where is RegressionTrainer？

### ISSUE THREAD

**Issue by ZJPure** [ethz-spylab/rlhf-poisoning#2]
from safe_rlhf.values.cost import CostTrainer
from safe_rlhf.values.reward import RewardTrainer
# from safe_rlhf.values.regression import RegressionTrainer

safe_rlhf.values has no regression

**Comment by javirandor** [comment]
Can you provide some additional details for me to reproduce this issue?

**Comment by javirandor** [comment]
Thanks for bringing this up. The issue should be fixed now. Let me know otherwise!
