### ISSUE TITLE
Bug in 'poison_data_oracle.py'

### ISSUE THREAD

**Issue by MisterPANDC** [ethz-spylab/rlhf-poisoning#4]
In the **oracle** poisoning, I believe the strategy is to poison samples with the maximum reward differences between the chosen and rejected response.
The preference dataset is sorted in the start: `dataset = dataset.sort(["correct", "difference"], reverse=True)`, but the actual poisoning samples are randomly sampled.
```python
random.seed(10)
all_idx = [i for i in range(len(dataset))]
random.shuffle(all_idx)
```

**Comment by javirandor** [comment]
Thanks for spotting this. I just merged a fix. I also double checked that the original codebase we use to run the experiments does not have this bug (so paper results are still valid).
